config/routes.rb
Rails.application.routes.draw do
  devise_scope :end_user do
    root "end_users/sessions#new"
  end
  devise_for :end_users, :controllers => {
    :sessions => 'end_users/sessions',
    :passwords => 'end_users/passwords',
    :registrations => 'end_users/registrations',
    :confirmations => 'end_users/confirmations'
  }
  scope module: :end_users do
    resources :end_users, only: [:index, :show]
    get '/end_users/:id/follow_index' => 'end_users#follow_index', as: 'follow_index'
    get '/end_users/:id/follower_index' => 'end_users#follower_index', as: 'follower_index'
    resources :appeals, only: [:index, :new, :create]
    post '/relationships/:followed_end_user_id' => 'relationships#create', as: 'follow'
    delete '/relationships/:unfollowed_end_user_id' => 'relationships#destroy', as: 'unfollow'
  end
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end

app/models/end_user.rb
class EndUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable, :authentication_keys => [:email_or_username]

  attr_accessor :email_or_username
  #email,usernameどちらでもログイン可能に
  def self.find_first_by_auth_conditions(warden_conditions)
    conditions = warden_conditions.dup
    if email_or_username = conditions.delete(:email_or_username)
      where(conditions).where(["username = :value OR lower(email) = lower(:value)", { :value => email_or_username }]).first
    else
      where(conditions).first
    end
  end

  validates :name, presence: true
  validates :username, presence: true
  validates :username, uniqueness: true, if: :username_presence_true?

  def username_presence_true?
    if username.present?
      true
    else
      false
    end
  end

  attachment :profile_image

  has_many :appeals, dependent: :destroy

  has_many :active_relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :following_users, through: :active_relationships, source: "followed"
  has_many :following_user_appeals, through: :following_users, source: "appeals"
  has_many :passive_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :followers, through: :passive_relationships, source: "follower"

  def follow(followed_end_user_id)
    relationship = Relationship.find_by(follower_id: self.id, followed_id: followed_end_user_id)
    unless relationship || self.id == followed_end_user_id
      Relationship.create(follower_id: self.id, followed_id: followed_end_user_id)
    end
  end

  def unfollow(unfollowed_end_user_id)
    relationship = Relationship.find_by(follower_id: self.id, followed_id: unfollowed_end_user_id)
    if relationship
      relationship.destroy
    end
  end
end

app/controllers/end_users/appeals_controller.rb
class EndUsers::AppealsController < ApplicationController

  before_action :authenticate_end_user!

  def index
    @latest_appeals = current_end_user.following_user_appeals.order(date_and_time: "DESC").limit(5)
    gon.latest_appeal_comments = Array.new
    gon.latest_appeal_lat_and_lon = Array.new(5).map{Array.new(2,0)}
    @latest_appeals.each_with_index do |appeal, index|
      gon.latest_appeal_comments << appeal.comment
      gon.latest_appeal_lat_and_lon[index][0] = appeal.latitude
      gon.latest_appeal_lat_and_lon[index][1] = appeal.longitude
    end
  end

  def new
    @new_appeal = Appeal.new
    gon.from = 0
  end

  def create
    @new_appeal = Appeal.new(appeal_params)
    @new_appeal.end_user_id = current_end_user.id
    if @new_appeal.save
      flash[:notice] = 'アピールを投稿しました'
      redirect_to appeals_path
    else
      if @new_appeal.latitude == nil || @new_appeal.longitude == nil
        gon.from = 0
        @new_appeal.add_lat_and_lon_error_message
      else
        gon.from = 1
        gon.new_appeal_lat = @new_appeal.latitude
        gon.new_appeal_log = @new_appeal.longitude
      end
      render :new
    end
  end

  private
  def appeal_params
    params.require(:appeal).permit(:comment, :date_and_time, :latitude, :longitude)
  end
end

app/controllers/end_users/confirmations_controller.rb
# frozen_string_literal: true

class EndUsers::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/end_users/end_users_controller.rb
class EndUsers::EndUsersController < ApplicationController
  before_action :authenticate_end_user!

  def index
    @all_end_users = EndUser.all
  end

  def search
  end

  def show
    @end_user = EndUser.find(params[:id])
    gon.latest_appeal_comments = Array.new
    gon.latest_appeal_lat_and_lon = Array.new(5).map{Array.new(2,0)}
    @end_user.appeals.each_with_index do |appeal, index|
      gon.latest_appeal_comments << appeal.comment
      gon.latest_appeal_lat_and_lon[index][0] = appeal.latitude
      gon.latest_appeal_lat_and_lon[index][1] = appeal.longitude
    end
  end

  def follow_index
    @end_user = EndUser.find(params[:id])
  end

  def follower_index
    @end_user = EndUser.find(params[:id])
  end

end

app/controllers/end_users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class EndUsers::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/end_users/passwords_controller.rb
# frozen_string_literal: true

class EndUsers::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/end_users/registrations_controller.rb
# frozen_string_literal: true

class EndUsers::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/end_users/relationships_controller.rb
class EndUsers::RelationshipsController < ApplicationController
  def create
    @end_user = EndUser.find(params[:followed_end_user_id])
    current_end_user.follow(@end_user.id)
  end
  def destroy
    @end_user = EndUser.find(params[:unfollowed_end_user_id])
    current_end_user.unfollow(@end_user.id)
  end
end

app/controllers/end_users/sessions_controller.rb
# frozen_string_literal: true

class EndUsers::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/end_users/unlocks_controller.rb
# frozen_string_literal: true

class EndUsers::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/end_users/appeals_helper.rb
module EndUsers::AppealsHelper
end

app/helpers/end_users/end_users_helper.rb
module EndUsers::EndUsersHelper
end

app/helpers/end_users/relationships_helper.rb
module EndUsers::RelationshipsHelper
end

app/views/end_users/end_users/follow_index.html.erb
<h2><%= @end_user.name %>さんのフォロー一覧</h2>
<table class='td-padding'>
  <tr>
    <th></th>
    <th>名前</th>
    <th>ユーザーネーム</th>
    <th></th>
  </tr>
  <% @end_user.following_users.each do |end_user| %>
  <tr>
    <td><%= attachment_image_tag end_user, :profile_image, size: '70x70', fallback: 'no-image.png' %></td>
    <td>
      <%= link_to end_user.name, end_user_path(end_user.id) %>
    </td>
    <td><%= end_user.username %></td>
    <td id='follow-button-user-id-<%= end_user.id %>'>
      <%= render partial: 'end_users/relationships/follow_button', locals: { end_user: end_user } %>
    </td>
  </tr>
  <% end %>
</table>

app/views/end_users/end_users/index.html.erb
<h1 id='user-index'>ユーザー一覧</h1>
<table class='user-index-table td-padding'>
  <tr>
    <th></th>
    <th>名前</th>
    <th>ユーザーネーム</th>
    <th>最新のアピール</th>
    <th></th>
  </tr>
  <% @all_end_users.each do |end_user| %>
  <tr>
    <td><%= attachment_image_tag end_user, :profile_image, size: '70x70', fallback: 'no-image.png' %></td>
    <td>
      <%= link_to end_user.name, end_user_path(end_user.id) %>
    </td>
    <td><%= end_user.username %></td>
    <!-- if文必要かも -->
    <% latest_appeal = end_user.appeals.order(date_and_time: 'DESC').limit(1) %>
    <td>
      <% if latest_appeal[0] %>
        <%= latest_appeal[0].date_and_time.strftime("%Y-%m-%d %H:%M") %>
      <% end %>
    </td>
    <td id='follow-button-user-id-<%= end_user.id %>'>
      <%= render partial: 'end_users/relationships/follow_button', locals: { end_user: end_user } %>
    </td>
  </tr>
  <% end %>
</table>

app/views/end_users/end_users/show.html.erb
<h1>ユーザー詳細</h1>
<div class="user-show-top">
  <div class="user-show-profile_image inline-block">
    <%= attachment_image_tag @end_user, :profile_image, size: '200x200', fallback: 'no-image.png' %>
  </div>
  <div class="user-show-info inline-block">
    <h2 class='user-show-name'><%= @end_user.name %></h2>
    <h3 class='user-show-username'>@<%= @end_user.username %></h3>
    <div class="user-show-info-bottom-flame">
      <div class="user-show-info-bottom user-show-info-bottom-left">
        <%= link_to "フォロー #{@end_user.active_relationships.count}", follow_index_path %>
      </div>
      <div class="user-show-info-bottom user-show-info-bottom-right">
        <%= link_to "フォロワー #{@end_user.passive_relationships.count}", follower_index_path %>
      </div>
    </div>
  </div>
</div>
<div class="user-show-middle">
  <div id="map" class='user-show-map'></div>
  <table class='user-show-table'>
    <tr>
      <th>comment</th>
      <th>datetime</th>
    </tr>
    <% @end_user.appeals.each do |appeal| %>
    <tr>
      <td><%= appeal.comment %></td>
      <td><%= appeal.date_and_time.strftime("%Y-%m-%d %H:%M") %></td>
    </tr>
    <% end %>
  </table>
</div>

<script type="text/javascript">
  function initMap(){
    let map = new google.maps.Map(document.getElementById('map'), {
      center: {lat: 35.680, lng: 139.767},
      zoom: 12
    });
    if(gon.latest_appeal_comments.length != 0){
      for (let i = 0; i < gon.latest_appeal_comments.length; i++){
        let markerLatLng = { lat: gon.latest_appeal_lat_and_lon[i][0], lng: gon.latest_appeal_lat_and_lon[i][1] };
        let marker = new google.maps.Marker({
          position: markerLatLng,
          map: map
        });
        let infoWindow = new google.maps.InfoWindow({
          content: `${gon.latest_appeal_comments[i]}`
        });
        infoWindow.open(map, marker)
      }
    }
  }
</script>
<script src="https://maps.googleapis.com/maps/api/js?key=<%= ENV['GOOGLE_MAPS_JAVASCRIPT_API_KEY'] %>&callback=initMap"></script>